### ISSUE TITLE
About importing apex and the basic environment

### ISSUE THREAD

**Issue by elliotcoupe** [surya501/loc2vec#1]
Hi, Suresh, I'm really appreciated to this implementation. But I'm stuck in the beginning.
I'm trying to run your code but got this error when I'm running trainer.py.
- from apex import amp (importt apex also didn't work).
_TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead._

I'm using python3.7 and similar issues about apex importing reported online are on the 3.5 online.
Thus, I want to confirm with you the environment you used in the project/ if it's possible to share a conda yml file for this project.
Best wishes.
Elliot

**Comment by surya501** [comment]
Apologies. When I experimented with this, I tried multiple things in the same conda environment and it was a mess. I didn't want to check the whole thing. While I made a todo item readme, I never got around to it. Thanks for nudging. 

Check the latest tip, along with the edits to the README. I didn't know how to compile apex using just conda. If you know how to do it, I'd appreciate a pull request for the same. Thx.

**Comment by elliotcoupe** [comment]
Many thanks. The new tips you provided is very helpful. 
However, If apex is required, is that means this project couldn't be run on Mac(since the official repo of  apex declared that the package is not tested on mac since there is no mac with nvidia GPU).
I'm currently exploring AWS to make this works, please stop me if it's not the case. 
Best.

**Comment by surya501** [comment]
You should be able to comment off apex support ( 3 lines of code and two includes in two loc2vec.py and trainer.py) and run it on any environment. Just don't uncomment the lines above it in the training loop.

I don't train on mac, just on a desktop linux box with gpu. Let me know how it goes on the mac.

**Comment by elliotcoupe** [comment]
I will run the code on mac, please bear with me.
Is this  aiming to save the tiles: cat urls.txt | xargs -P 10 -n 1 wget -nH -nc -x
it ends with a error: xargs: wget: No such file or directory

**Comment by elliotcoupe** [comment]
I tried the shell in my linux vm. It works. Cheers
